const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const topics=['foundations','design','qc','pca','association','validation','plink','ld'];
const next={foundations:'design',design:'qc',qc:'pca',pca:'association',association:'validation',validation:'plink',plink:'ld',ld:'quiz'};
const state={completed:new Set(JSON.parse(localStorage.getItem('gwas-v3-complete')||'[]')),screen:'intro'};
function show(id){if(id==='quiz'&&state.completed.size<8)return;state.screen=id;$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));$$('[data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===id));$('#rail').classList.remove('open');location.hash=id;scrollTo(0,0)}
$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));$('#menuBtn').onclick=()=>$('#rail').classList.toggle('open');
function syncProgress(){topics.forEach(t=>{const nav=$(`#topicNav [data-go="${t}"]`);nav.classList.toggle('complete',state.completed.has(t))});const n=state.completed.size;$('#progressLabel').textContent=`${n} / 8 topics`;$('#progressBar').style.width=n/8*100+'%';$('#quizNav').disabled=n<8;$('#quizNav').querySelector('i').textContent=n===8?'':'🔒';$('#quizLocked').hidden=n===8;$('#quizReady').hidden=n<8;localStorage.setItem('gwas-v3-complete',JSON.stringify([...state.completed]))}
function complete(topic){state.completed.add(topic);syncProgress();if(topic==='ld')makeQuiz();show(next[topic])}
topics.forEach(t=>$(`#${t}Done`).onclick=()=>complete(t));$('#resetBtn').onclick=()=>{if(confirm('Reset all topics and the final quiz?')){const currentQuiz=localStorage.getItem('gwas-v3-quiz');if(currentQuiz)localStorage.setItem('gwas-v3-last-quiz',currentQuiz);localStorage.removeItem('gwas-v3-complete');localStorage.removeItem('gwas-v3-quiz');localStorage.removeItem('gwas-v3-quiz-result');location.hash='intro';location.reload()}};syncProgress();

const chosenAlleles=['',''];
function foundationCheck(){const g=+$('#vg').value,e=+$('#ve').value,h=g/(g+e),filled=chosenAlleles.every(Boolean),dose=chosenAlleles.filter(a=>a==='G').length;$('#vgOut').textContent=g;$('#veOut').textContent=e;$('#h2Out').textContent=h.toFixed(2);$('#gBar').style.width=h*100+'%';$('#eBar').style.width=(1-h)*100+'%';$('#genoStatus').textContent=filled?`EFFECT ALLELE DOSAGE = ${dose}`:'CHOOSE BOTH ALLELES';const ok=Math.abs(h-.6)<.001&&filled&&dose===1;$('#foundationsDone').disabled=!ok;$('#foundationsHint').textContent=ok?'Checkpoint ready.':'Match h² = 0.60 and effect allele dosage = 1.'}
['vg','ve'].forEach(id=>$('#'+id).oninput=foundationCheck);$$('[data-slot]').forEach(b=>b.onclick=()=>{const slot=+b.dataset.slot;chosenAlleles[slot]=b.dataset.allele;$$(`[data-slot="${slot}"]`).forEach(x=>x.classList.toggle('selected',x===b));$('#allele'+(slot+1)).textContent=b.dataset.allele;foundationCheck()});foundationCheck();

const designSeen={pos:false,neg:false,pcs:false};let lastDesignBeta=0;
function designCalc(){const or=+$('#caseC').value*+$('#ctrlT').value/(+$('#caseT').value*+ +$('#ctrlC').value),beta=Math.log(or);lastDesignBeta=beta;$('#designOR').textContent=isFinite(or)?or.toFixed(2):'—';$('#designBeta').textContent=isFinite(beta)?`${beta>=0?'+':''}${beta.toFixed(3)}`:'—';const positive=beta>=0;$('#designEffect').className='effect-readout '+(positive?'positive':'negative');if(beta>.05)designSeen.pos=true;if(beta<-.05)designSeen.neg=true;$('#seenPos').textContent=(designSeen.pos?'✓':'○')+' +β';$('#seenNeg').textContent=(designSeen.neg?'✓':'○')+' −β';$('#seenPos').classList.toggle('hit',designSeen.pos);$('#seenNeg').classList.toggle('hit',designSeen.neg);renderConfound();designCheck()}
['caseC','caseT','ctrlC','ctrlT'].forEach(id=>$('#'+id).oninput=designCalc);$('#riskPreset').onclick=()=>{$('#caseC').value=620;$('#caseT').value=490;$('#ctrlC').value=380;$('#ctrlT').value=510;designCalc()};$('#protectPreset').onclick=()=>{$('#caseC').value=380;$('#caseT').value=510;$('#ctrlC').value=620;$('#ctrlT').value=490;designCalc()};
function renderConfound(){const casePct=70,controlPct=30,raw=Math.exp(lastDesignBeta),bias=.35*(casePct-controlPct)/100,adjusted=Math.exp(lastDesignBeta-Math.sign(lastDesignBeta||1)*bias);$('#caseConfBar').style.width=casePct+'%';$('#controlConfBar').style.width=controlPct+'%';$('#crudeOR').textContent=isFinite(raw)?raw.toFixed(2):'—';$('#adjustedOR').textContent=isFinite(raw)?(designSeen.pcs?adjusted:raw).toFixed(2):'—';$('#adjustLabel').textContent=designSeen.pcs?'ADJUSTED OR':'UNADJUSTED';}
$('#pcToggle').onclick=()=>{designSeen.pcs=!designSeen.pcs;$('#pcToggle').classList.toggle('on',designSeen.pcs);$('#confoundStatus').className='mini-status '+(designSeen.pcs?'safe':'danger');$('#confoundStatus').textContent=designSeen.pcs?'REWEIGHTED TO THE SAME CONFOUNDER MIX':'CASES 70% · CONTROLS 30%';renderConfound();designCheck()};function designCheck(){const ok=designSeen.pos&&designSeen.neg&&designSeen.pcs;$('#designDone').disabled=!ok;$('#designHint').textContent=ok?'Checkpoint ready.':'View both effect directions and adjust the confounder.'}designCalc();

const snps=[
 {id:'rs101',call:99,maf:12,hwe:3e-2},{id:'rs102',call:93,maf:18,hwe:2e-2},{id:'rs103',call:98,maf:.4,hwe:4e-2},{id:'rs104',call:97,maf:7,hwe:2e-8}
];
const samples=[
 {id:'P01',miss:.2,het:.3,sex:true},{id:'P02',miss:2.2,het:.4,sex:true},{id:'P03',miss:.5,het:3.7,sex:true},{id:'P04',miss:.3,het:-.4,sex:false}
];
const pairs=[{id:'P05–P06',a:'P05',b:'P06',kin:.5},{id:'P07–P08',a:'P07',b:'P08',kin:.25},{id:'P09–P10',a:'P09',b:'P10',kin:.125},{id:'P11–P12',a:'P11',b:'P12',kin:.0625}];
const qcAnswers={snps:{},samples:{},pairs:{}};let qcTab='snps';
function qcThresholds(){const exp=+$('#hwe').value;$('#snpCallO').textContent=$('#snpCall').value+'%';$('#mafO').textContent=$('#maf').value+'%';$('#hweO').textContent=`1e−${exp}`;$('#missO').textContent=$('#miss').value+'%';$('#hetO').textContent=`±${$('#het').value} SD`;$('#kinO').textContent=(+$('#kin').value).toFixed(4);const bars=Array.from({length:28},(_,i)=>`<i style="height:${10+Math.abs(Math.sin(i*1.8))*50+(i===23?18:0)}px"></i>`).join('');$('#hweDist').innerHTML=bars;$('#hetDist').innerHTML=Array.from({length:25},(_,i)=>`<i style="height:${10+60*Math.exp(-Math.pow((i-12)/6,2))}px"></i>`).join('');qcCheck()}
['snpCall','maf','hwe','miss','het','kin'].forEach(id=>$('#'+id).oninput=qcThresholds);
function decide(kind,id,value){qcAnswers[kind][id]=value;renderQC()}
function renderQC(){const box=$('#qcExamples');if(qcTab==='snps'||qcTab==='samples'){const arr=qcTab==='snps'?snps:samples;box.className='decision-list';box.innerHTML=arr.map(x=>`<div class="decision"><b>${x.id}</b><div class="decide"><button class="keep ${qcAnswers[qcTab][x.id]==='keep'?'selected':''}" data-kind="${qcTab}" data-id="${x.id}" data-v="keep">KEEP</button><button class="drop ${qcAnswers[qcTab][x.id]==='drop'?'selected':''}" data-kind="${qcTab}" data-id="${x.id}" data-v="drop">REMOVE</button></div><p>${qcTab==='snps'?`call ${x.call}% · MAF ${x.maf}% · HWE ${x.hwe.toExponential(1)}`:`missing ${x.miss}% · het Z ${x.het} · sex ${x.sex?'match':'MISMATCH'}`}</p></div>`).join('');$$('.decide button').forEach(b=>b.onclick=()=>decide(b.dataset.kind,b.dataset.id,b.dataset.v))}else{box.className='';box.innerHTML=pairs.map(p=>`<div class="pair-card"><b>${p.id}</b> · kinship ${p.kin}<div><button class="${qcAnswers.pairs[p.id]==='both'?'selected':''}" data-pair="${p.id}" data-sample="both">KEEP BOTH</button><button class="${qcAnswers.pairs[p.id]===p.a?'selected':''}" data-pair="${p.id}" data-sample="${p.a}">KEEP ${p.a}</button><button class="${qcAnswers.pairs[p.id]===p.b?'selected':''}" data-pair="${p.id}" data-sample="${p.b}">KEEP ${p.b}</button></div></div>`).join('');$$('[data-pair]').forEach(b=>b.onclick=()=>{qcAnswers.pairs[b.dataset.pair]=b.dataset.sample;renderQC()})}qcCheck()}
$$('[data-qctab]').forEach(b=>b.onclick=()=>{qcTab=b.dataset.qctab;$$('[data-qctab]').forEach(x=>x.classList.toggle('active',x===b));renderQC()});
function qcCheck(){let correct=0,total=snps.length+samples.length+pairs.length;const call=+$('#snpCall').value,maf=+$('#maf').value,hwe=Math.pow(10,-+$('#hwe').value),miss=+$('#miss').value,het=+$('#het').value,kin=+$('#kin').value;snps.forEach(x=>{const expected=x.call>=call&&x.maf>=maf&&x.hwe>=hwe?'keep':'drop';if(qcAnswers.snps[x.id]===expected)correct++});samples.forEach(x=>{const expected=x.miss<=miss&&Math.abs(x.het)<=het&&x.sex?'keep':'drop';if(qcAnswers.samples[x.id]===expected)correct++});pairs.forEach(p=>{const answer=qcAnswers.pairs[p.id],expected=p.kin<=kin?'both':'one';if((expected==='both'&&answer==='both')||(expected==='one'&&(answer===p.a||answer===p.b)))correct++});$('#qcScore').textContent=`${correct} / ${total} correct for current thresholds`;const ok=correct===total;$('#qcDone').disabled=!ok;$('#qcHint').textContent=ok?'Checkpoint ready.':'Classify every item using the current thresholds on the left.'}qcThresholds();renderQC();

const pcaSeen=new Set();const ancestryDefs=[['Japanese',170,245,'#087bb5'],['Han Chinese',330,260,'#9a62d6'],['Southeast Asian',485,285,'#ff8a3d'],['South Asian',640,300,'#19a474'],['Asian Indian',640,405,'#20c4cb']];const pcaPts=[];ancestryDefs.forEach((d,g)=>{for(let i=0;i<38;i++)pcaPts.push({g,x:d[1]+Math.sin(i*2.35+g)*62+(i%5)*3,y:d[2]+Math.cos(i*1.73+g)*44,sex:i%2,t2dm:(i+g*2)%7<2,htn:(i*2+g)%8<3})});
function renderPCA(mode){pcaSeen.add(mode);const palettes={sex:['#087bb5','#db4051'],t2dm:['#9eafb7','#db4051'],htn:['#9eafb7','#ff8a3d']};let s='<path d="M55 25v470h725" stroke="#91a6b0" fill="none"/><text x="742" y="525">PC1</text><text x="12" y="34">PC2</text>';pcaPts.forEach(p=>{const color=mode==='ancestry'?ancestryDefs[p.g][3]:palettes[mode][p[mode]?1:0];s+=`<circle cx="${p.x}" cy="${p.y}" r="6" fill="${color}" opacity=".78"/>`});if(mode==='ancestry')ancestryDefs.forEach(d=>s+=`<text x="${d[1]-18}" y="${d[2]-62}" fill="${d[3]}" font-weight="bold">${d[0]}</text>`);$('#pcaPlot').innerHTML=s;const legends=mode==='ancestry'?ancestryDefs.map(d=>[d[0],d[3]]):mode==='sex'?[['MALE','#087bb5'],['FEMALE','#db4051']]:mode==='t2dm'?[['CONTROL','#9eafb7'],['T2DM','#db4051']]:[['CONTROL','#9eafb7'],['HYPERTENSION','#ff8a3d']];$('#pcaLegend').innerHTML=legends.map(x=>`<span><i style="background:${x[1]}"></i>${x[0]}</span>`).join('');$$('#pcaModes button').forEach(b=>{b.classList.toggle('active',b.dataset.mode===mode);b.classList.toggle('viewed',pcaSeen.has(b.dataset.mode))});$('#pcaViewed').textContent=`${pcaSeen.size} / 4 views`;$('#pcaDone').disabled=pcaSeen.size<4;$('#pcaHint').textContent=pcaSeen.size===4?'Checkpoint ready.':'Switch through every phenotype and ancestry view.'}
$$('#pcaModes button').forEach(b=>b.onclick=()=>renderPCA(b.dataset.mode));renderPCA('ancestry');

let assocModel='logistic';$$('[data-model]').forEach(b=>b.onclick=()=>{assocModel=b.dataset.model;$$('[data-model]').forEach(x=>x.classList.toggle('selected',x===b));associationUpdate()});['covAge','covSex','covPC'].forEach(id=>$('#'+id).onchange=associationUpdate);function associationUpdate(){let beta=.42;const terms=[];if($('#covAge').checked){beta-=.06;terms.push('AGE')}if($('#covSex').checked){beta-=.04;terms.push('SEX')}if($('#covPC').checked){beta-=.11;terms.push('PC1…PC5')}const or=Math.exp(beta);$('#assocBeta').textContent=`${beta>=0?'+':''}${beta.toFixed(2)}`;$('#assocOR').textContent=or.toFixed(3);$('#forestDot').style.left=Math.max(2,Math.min(96,50+beta*70))+'%';$('#assocFormula').innerHTML=(assocModel==='logistic'?'logit[P(Y=1)]':'Y')+' = α + β<sub>SNP</sub>SNP'+(terms.length?'<br>+ '+terms.join(' + '):'');const ok=terms.length===3;$('#assocStatus').className='mini-status '+(ok?'safe':'danger');$('#assocStatus').textContent=ok?'COVARIATES COMPLETE':'CONFOUNDING NOT FULLY ADJUSTED';$('#associationDone').disabled=!ok;$('#associationHint').textContent=ok?'Checkpoint ready.':'Add AGE, SEX, and PC1–PC5.'}associationUpdate();

const thresholds=[{label:'1×10⁻⁵',y:5},{label:'1×10⁻⁶',y:6},{label:'1×10⁻⁷',y:7},{label:'5×10⁻⁸',y:7.301},{label:'1×10⁻⁸',y:8},{label:'1×10⁻⁹',y:9}];let inflationSeen=false;const manPts=[];for(let chr=1;chr<=22;chr++)for(let i=0;i<18;i++){let y=1.15+Math.abs(Math.sin(chr*5.31+i*2.47))*3.2;if((chr===6&&i===11)||(chr===12&&i===5))y+=5.2;if(chr===3&&i===8)y+=3.4;if(chr===2&&i===4)y=5.4;if(chr===4&&i===2)y=6.4;if(chr===8&&i===7)y=7.15;manPts.push({chr,i,y})}
function renderValidation(){const th=thresholds[+$('#pThreshold').value],lambda=+$('#lambda').value;$('#pThresholdO').textContent=th.label;$('#lambdaO').textContent=lambda.toFixed(2);if(lambda>=1.15)inflationSeen=true;let s='<path d="M52 28v386h920" stroke="#8ca1ac" fill="none"/>';for(let chr=1;chr<=22;chr++){const x=62+(chr-1)/21*890;s+=`<text x="${x}" y="452" text-anchor="middle" font-size="15">${chr}</text>`}const lineY=414-th.y/11*350;s+=`<line x1="52" y1="${lineY}" x2="972" y2="${lineY}" stroke="#db4051" stroke-width="3" stroke-dasharray="7 5"/>`;let sig=0;manPts.forEach((p,j)=>{const x=62+((p.chr-1)+(p.i/18))/22*900,yy=p.y+(lambda-1)*7,y=414-Math.min(yy,11)/11*350,isSig=yy>=th.y;if(isSig)sig++;s+=`<circle data-locus="${j}" cx="${x}" cy="${y}" r="${isSig?5.5:3.2}" fill="${isSig?'#db4051':p.chr%2?'#087bb5':'#21c6cb'}" opacity="${isSig?1:.72}"/>`});$('#manhattanPlot').innerHTML=s;$('#sigCount').textContent=`${sig} significant loci`;$$('[data-locus]').forEach(c=>c.onclick=()=>{const p=manPts[+c.dataset.locus],yy=p.y+(lambda-1)*7;$('#locusDetail').textContent=`CHR ${p.chr} · −LOG10(P) ${yy.toFixed(2)} · ${yy>=th.y?'SIGNIFICANT':'BELOW THRESHOLD'}`});let q='<path d="M40 20v250h285M42 268 310 32" stroke="#91a6b0" fill="none"/><text x="210" y="300">EXPECTED −log₁₀(P)</text>';for(let i=1;i<=18;i++){const x=43+i*14.2,obs=i*14.2+(lambda-1)*i*i*.55;q+=`<circle cx="${x}" cy="${270-Math.min(obs,235)}" r="4" fill="${lambda>1.1?'#db4051':'#087bb5'}"/>`}$('#qqPlot').innerHTML=q;$('#inflatedChi').textContent=lambda.toFixed(2)+'×χ²';$('#noiseLift').textContent=lambda>1.1?'NOISE LIFTED':'BASELINE';$('#lambdaStatus').className='mini-status '+(lambda>1.1?'danger':'safe');$('#lambdaStatus').textContent=lambda>1.1?'λGC > 1 · GLOBAL INFLATION':'λGC ≈ 1 · CALIBRATED';const ok=+$('#pThreshold').value===3&&Math.abs(lambda-1)<.001&&inflationSeen;$('#validationDone').disabled=!ok;$('#validationHint').textContent=ok?'Checkpoint ready.':'Set 5×10⁻⁸, explore λGC ≥ 1.15, then return to 1.00.'}
$('#pThreshold').oninput=renderValidation;$('#lambda').oninput=renderValidation;renderValidation();

const plinkSeen=new Set(),plinkCommands=[];let plinkFile='raw';const shuffled=[...$('#plinkSteps').children].sort(()=>Math.random()-.5);shuffled.forEach(b=>$('#plinkSteps').appendChild(b));function resetPlink(error){plinkSeen.clear();plinkCommands.length=0;plinkFile='raw';$$('#plinkSteps button').forEach(x=>x.classList.remove('ran'));$('#codeBox').textContent='SELECT SNP QC OR SAMPLE QC';$('#consoleBox').textContent='⚠ '+error+' Progress cleared—start again.';$('#consoleBox').className='console error';$('#plinkDone').disabled=true;$('#plinkHint').textContent='Run both QC steps before PCA.'}$$('#plinkSteps button').forEach(b=>b.onclick=()=>{const step=b.dataset.code,isQc=step==='snp'||step==='sample',bothQc=plinkSeen.has('snp')&&plinkSeen.has('sample');const allowed=isQc&&!plinkSeen.has(step)&&!plinkSeen.has('pca')||step==='pca'&&bothQc&&!plinkSeen.has('pca')||step==='assoc'&&plinkSeen.has('pca')&&!plinkSeen.has('assoc');if(!allowed){let error='Incorrect workflow order.';if(step==='pca'&&!bothQc)error='Complete both SNP QC and Sample QC before PCA.';else if(step==='assoc'&&!plinkSeen.has('sample'))error='Results are biased by individuals!';else if(step==='assoc'&&!plinkSeen.has('pca'))error='PC1–PC5 are missing!';resetPlink(error);return}let command;if(step==='snp'){command=`plink2 --pfile ${plinkFile} --geno 0.05 --maf 0.01 --hwe 1e-6 --make-pgen --out snp_qc`;plinkFile='snp_qc'}else if(step==='sample'){command=`plink2 --pfile ${plinkFile} --mind 0.01 --check-sex --het --make-pgen --out sample_qc`;plinkFile='sample_qc'}else if(step==='pca')command=`plink2 --pfile ${plinkFile} --pca 5 --out ancestry`;else command=`plink2 --pfile ${plinkFile} --glm --covar ancestry.eigenvec --covar-name AGE,SEX,PC1-PC5`;plinkSeen.add(step);plinkCommands.push('$ '+command);$('#codeBox').textContent=plinkCommands.join('\n\n');$('#consoleBox').textContent=`✓ ${b.textContent.trim()} complete`;$('#consoleBox').className='console';b.classList.add('ran');$('#plinkDone').disabled=plinkSeen.size<4;$('#plinkHint').textContent=plinkSeen.size===4?'Checkpoint ready.':`${plinkSeen.size} / 4 correct steps.`});

const haplotypes={R1:[...'ACTGACTGAC'],R2:[...'GTCAGTCCAG'],R3:[...'AGGCTAAGCT'],R4:[...'CTACGTGCTA'],R5:[...'TCGAACTAGG'],R6:[...'AATGCGATCC']};const ldBlocks=[[0,3],[3,7],[7,10]],knownAlleles={0:'G',3:'C',6:'G',7:'A'};let activeBlock=0,blockChoices=[null,null,null];
function renderLD(){const n=10,blocks=[[0,2],[3,6],[7,9]];let s='<g transform="rotate(90 260 240)"><g transform="translate(95,55) rotate(45 130 130)">';for(let r=0;r<n;r++)for(let c=0;c<=r;c++){let same=blocks.some(b=>r>=b[0]&&r<=b[1]&&c>=b[0]&&c<=b[1]),d=Math.abs(r-c),v=same?Math.max(.35,.96-d*.15):Math.max(.04,.22-d*.02);if((r===6&&c===2)||(r===9&&c===7))v=.55;const color=v>.7?'#9f142f':v>.35?'#e46155':v>.15?'#ef9b84':'#f5ddd3';s+=`<rect x="${c*25}" y="${r*25}" width="23" height="23" fill="${color}"><title>Loci ${c+1}–${r+1} · r² ${v.toFixed(2)}</title></rect>`}s+='</g></g><text x="70" y="455">1–3</text><text x="235" y="455">4–7</text><text x="395" y="455">8–10</text>';$('#ldMatrix').innerHTML=s}renderLD();
function blockClass(i){return i<3?'block-a':i<7?'block-b':'block-c'}function renderHaps(){const loci=Array.from({length:10},(_,i)=>`<i class="${blockClass(i)}">${i+1}</i>`).join('');$('#referencePanel').innerHTML=`<div class="hap-row"><b>LOCUS</b>${loci}</div>`+Object.entries(haplotypes).map(([id,a])=>{const used=blockChoices.map((x,i)=>x===id?i+1:null).filter(Boolean).join(',');return `<div class="hap-row"><button data-hap="${id}" class="${blockChoices[activeBlock]===id?'selected':''}">${id}${used?` · B${used}`:''}</button>${a.map((v,i)=>`<i class="${blockClass(i)} ${i>=ldBlocks[activeBlock][0]&&i<ldBlocks[activeBlock][1]?'focus':''}">${v}</i>`).join('')}</div>`}).join('');$$('[data-hap]').forEach(b=>b.onclick=()=>{blockChoices[activeBlock]=b.dataset.hap;$('#blockChoice'+activeBlock).textContent=b.dataset.hap;const next=blockChoices.findIndex(x=>!x);if(next>=0)activeBlock=next;$$('[data-block]').forEach(x=>x.classList.toggle('active',+x.dataset.block===activeBlock));$('#imputeBtn').disabled=blockChoices.some(x=>!x);$('#ldDone').disabled=true;renderHaps()})}$$('[data-block]').forEach(b=>b.onclick=()=>{activeBlock=+b.dataset.block;$$('[data-block]').forEach(x=>x.classList.toggle('active',x===b));renderHaps()});renderHaps();$('#targetTyped').innerHTML='<b>TARGET</b>'+Array.from({length:10},(_,i)=>`<i class="${blockClass(i)} ${knownAlleles[i]?'typed':''}">${knownAlleles[i]||'?'}</i>`).join('');$('#imputeBtn').onclick=()=>{const seqs=blockChoices.map(id=>haplotypes[id]),valid=[seqs[0][0]==='G',seqs[1][3]==='C'&&seqs[1][6]==='G',seqs[2][7]==='A'];if(valid.every(Boolean)){const imputed=[...seqs[0].slice(0,3),...seqs[1].slice(3,7),...seqs[2].slice(7,10)];$('#imputedResult').innerHTML='<b>IMPUTED</b>'+imputed.map((v,i)=>`<i class="${knownAlleles[i]?'typed':'inferred'}">${v}</i>`).join('');$('#ldHint').textContent='All three LD blocks match. Checkpoint ready.';$('#ldDone').disabled=false}else{const bad=valid.map((v,i)=>v?'':`BLOCK ${i+1}`).filter(Boolean).join(' · ');$('#imputedResult').innerHTML=`<b>NO MATCH</b><span style="grid-column:2/-1">${bad} conflicts with the known target alleles.</span>`;$('#ldHint').textContent='Replace the mismatched reference sequence.';$('#ldDone').disabled=true}};

const questionPool=[
 ['Heritability h² is…',['population-level variance explained','an individual genetic percentage'],0],['AG additive dosage is…',['0','1','2'],1],['If OR = 0.7, β is…',['positive','negative'],1],['β for an odds ratio equals…',['ln(OR)','OR²'],0],['Ancestry imbalance can create…',['spurious association','higher call rate'],0],['Principal components commonly adjust…',['population structure','reference allele coding'],0],['SNP QC includes…',['MAF','sample sex check'],0],['Sample QC includes…',['heterozygosity','SNP HWE only'],0],['A low SNP call rate suggests…',['genotyping failure','strong association'],0],['Extreme heterozygosity may suggest…',['contamination or inbreeding','high imputation certainty'],0],['Related pairs violate…',['sample independence','Hardy–Weinberg algebra'],0],['Binary outcomes commonly use…',['logistic regression','linear regression only'],0],['Adding covariates may change…',['β and OR','chromosome position'],0],['Genome-wide significance is commonly…',['5×10⁻⁸','0.05'],0],['λGC > 1 can indicate…',['global inflation','perfect calibration'],0],['Manhattan x-axis usually shows…',['chromosomes','samples'],0],['High LD means loci are…',['correlated','always causal'],0],['LD patterns are…',['population-specific','identical worldwide'],0],['Genotype imputation uses…',['reference haplotypes','phenotypes only'],0],['Poor imputation quality should be…',['filtered','treated as typed'],0]
];
let quizSet=[],quizAnswers={},quizSubmitted=false;function randomIndex(n){if(globalThis.crypto?.getRandomValues){const a=new Uint32Array(1);globalThis.crypto.getRandomValues(a);return Math.floor(a[0]/4294967296*n)}return Math.floor(Math.random()*n)}function drawQuiz(){const last=JSON.parse(localStorage.getItem('gwas-v3-last-quiz')||'null');let picked;do{const pool=[...questionPool.keys()];for(let i=pool.length-1;i>0;i--){const j=randomIndex(i+1);[pool[i],pool[j]]=[pool[j],pool[i]]}picked=pool.slice(0,8)}while(Array.isArray(last)&&last.length===8&&picked.every(i=>last.includes(i)));return picked}function gradeQuiz(restored=false){if(Object.keys(quizAnswers).length<8)return;quizSubmitted=true;const score=Object.keys(quizAnswers).filter(i=>quizAnswers[i]===quizSet[i][2]).length;$$('[data-qi]').forEach(b=>{const i=+b.dataset.qi,a=+b.dataset.qa;b.disabled=true;b.className=a===quizSet[i][2]?'correct':(a===quizAnswers[i]?'wrong':'')});$('#quizScore').textContent=`${score} / 8`;$('#quizResult').hidden=false;$('#submitQuiz').hidden=true;if(!restored)localStorage.setItem('gwas-v3-quiz-result',JSON.stringify({answers:quizAnswers,submitted:true}))}function makeQuiz(){if(state.completed.size<8)return;let picked=JSON.parse(localStorage.getItem('gwas-v3-quiz')||'null');if(!Array.isArray(picked)||picked.length!==8){picked=drawQuiz();localStorage.setItem('gwas-v3-quiz',JSON.stringify(picked))}quizSet=picked.map(i=>questionPool[i]);const saved=JSON.parse(localStorage.getItem('gwas-v3-quiz-result')||'null');quizAnswers=saved?.answers||{};quizSubmitted=!!saved?.submitted;$('#quizGrid').innerHTML=quizSet.map((q,i)=>`<article class="quiz-card"><b>${i+1}. ${q[0]}</b>${q[1].map((a,j)=>`<button data-qi="${i}" data-qa="${j}" class="${quizAnswers[i]===j?'selected':''}">${a}</button>`).join('')}</article>`).join('');$('#quizResult').hidden=true;$('#submitQuiz').hidden=Object.keys(quizAnswers).length<8;$$('[data-qi]').forEach(b=>b.onclick=()=>{if(quizSubmitted)return;const i=+b.dataset.qi,a=+b.dataset.qa;quizAnswers[i]=a;b.parentElement.querySelectorAll('button').forEach(x=>x.classList.toggle('selected',+x.dataset.qa===a));$('#submitQuiz').hidden=Object.keys(quizAnswers).length<8});if(quizSubmitted)gradeQuiz(true)}$('#submitQuiz').onclick=()=>gradeQuiz(false);if(state.completed.size===8)makeQuiz();
const initial=location.hash.slice(1);show(initial&&document.getElementById(initial)&&!(initial==='quiz'&&state.completed.size<8)?initial:'intro');
